-- SPUFI CREATE TABLE

CREATE TABLE TACUENT (
     NUMERO_CUENTA     CHAR(10)       NOT NULL
   , CEDULA_CLIENTE    CHAR(10)       NOT NULL
   , NOMBRE_CLIENTE    CHAR(50)       NOT NULL
   , SALDO             DECIMAL(15,2)  NOT NULL
   , ESTADO_CUENTA     CHAR(1)        NOT NULL

   , PRIMARY KEY (NUMERO_CUENTA)
   ) IN BANCODB.CUENTAS;
   CREATE UNIQUE INDEX TACUENT_IPK ON TACUENT (NUMERO_CUENTA);

CREATE TABLE TATRANS (
     ID_TRANSACTION   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY
   , NUMERO_CUENTA_T  CHAR(10) NOT NULL
   , TIPO_TRANSACCION CHAR(1)  NOT NULL
   , MONTO            DECIMAL(15,2)
   , FECHA_HORA       TIMESTAMP NOT NULL

    ) IN BANCODB.TRANSACT;
    CREATE INDEX IDX_TATRANS_CUENTA ON TATRANS (NUMERO_CUENTA_T);

    ALTER TABLE TATRANS
    ADD CONSTRAINT FK_TRANS_TACUENT
    FOREIGN KEY (NUMERO_CUENTA_T)
    REFERENCES TACUENT(NUMERO_CUENTA)
    ON DELETE CASCADE;

CREATE TABLE TAESTLOG (
    ID_LOG            INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY
  , NUMERO_CUENTA_L   CHAR(10)   NOT NULL
  , ESTADO_CUENTA_L   CHAR(1)    NOT NULL
  , ESTADO_NUEVO      CHAR(1)    NOT NULL
  , FECHA_HORA        TIMESTAMP  NOT NULL

    ) IN BANCODB.ESTCUENT;
    CREATE INDEX IDX_TAESTLOG_CUENTA ON TAESTLOG (NUMERO_CUENTA_L);

    ALTER TABLE TAESTLOG
    ADD CONSTRAINT FK_LOG_TACUENT
    FOREIGN KEY (NUMERO_CUENTA_L)
    REFERENCES TACUENT(NUMERO_CUENTA)
    ON DELETE CASCADE
