-- SPUFI CREATE TABLESPACE

CREATE TABLESPACE CUENTAS
  IN BANCODB
  USING STOGROUP BANCOSG
  PRIQTY 250
  SECQTY 100
  ERASE NO
  FREEPAGE 10
  PCTFREE 10
  BUFFERPOOL BP1
  COMPRESS NO
  LOCKSIZE ANY
  LOCKMAX SYSTEM
  CLOSE YES;

CREATE TABLESPACE TRANSACT
  IN BANCODB
  USING STOGROUP BANCOSG
  PRIQTY 250
  SECQTY 100
  ERASE NO
  FREEPAGE 10
  PCTFREE 10
  BUFFERPOOL BP1
  COMPRESS NO
  LOCKSIZE ANY
  LOCKMAX SYSTEM
  CLOSE YES;

CREATE TABLESPACE ESTCUENT
  IN BANCODB
  USING STOGROUP BANCOSG
  PRIQTY 250
  SECQTY 100
  ERASE NO
  FREEPAGE 10
  PCTFREE 10
  BUFFERPOOL BP1
  COMPRESS NO
  LOCKSIZE ANY
  LOCKMAX SYSTEM
  CLOSE YES;
